# Generated by Django 3.2.3 on 2021-05-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.CharField(max_length=300)),
                ('duration', models.FloatField()),
                ('transcript', models.CharField(max_length=300)),
            ],
        ),
    ]
