# Generated by Django 3.2.3 on 2021-06-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getter', '0003_audio_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='sample_rate',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='audio',
            name='source',
            field=models.CharField(default='喜马拉雅', max_length=300),
            preserve_default=False,
        ),
    ]
